### ISSUE TITLE
😭  What's this?

### ISSUE THREAD

**Issue by Nbsaw** [makegirlsmoe/makegirls.moe_web#1]
![bd h f ex4h6p 29zz0i y](https://user-images.githubusercontent.com/12481935/29249728-a5b9d4b4-8067-11e7-859e-2e7a7268cd4c.png)

**Comment by Aixile** [comment]
Actually, we didn't remove images of male characters in our training dataset, thus some results will be male characters...
Note that our subtitle is "create anime characters with A.I." not "create anime girls with A.I."
I use the domain make.girls.moe just because I own the domain girls.moe

**Comment by Nbsaw** [comment]
@Aixile
