### ISSUE TITLE
Feature Request: Tweet a facial image with a noise image

### ISSUE THREAD

**Issue by fukueto** [makegirlsmoe/makegirls.moe_web#13]
Thank you for your great app!
When I see cute girl images that other users generated and shared on Twitter, I would like to get their noises and reproduce them.
How about adding a noise image to a tweet by default when sharing a facial image on Twitter?

**Comment by zhangjk95** [comment]
Thank you for your suggestion. The new feature is added. https://github.com/makegirlsmoe/makegirls.moe_web/commit/e364275101aa2c211865fd42d81320aa3433d93f We noticed that sharing two images at the same time makes the tweet look not good. So this feature is not enabled by default unless you manually enable it when sharing on twitter.

**Comment by fukueto** [comment]
Thank you very much for the feature!
It is so nice to be able to share a noise easily on Twitter.
I will try it :)
