### ISSUE TITLE
store data from generated images  to future model training

### ISSUE THREAD

**Issue by Andmat7** [makegirlsmoe/makegirls.moe_web#14]
For example:
* Is it a boy or a girl?
![](https://pbs.twimg.com/media/DHZjsHkXYAEKxd5.jpg)
* Is it a teenager, a girl or an adult?
![](https://pbs.twimg.com/media/DHcQ5Y4VwAEtoF-.jpg)
![](https://pbs.twimg.com/media/DHb-vpsUIAEJV9x.jpg)
* face position.
and if possible share it

**Comment by zhangjk95** [comment]
Currently we don't have a model that can automatically classify generated images (such as whether it is a boy or a girl). But we are storing noise and conditions(no matter they are random or specified by users), which can reproduce the generated images, along with user ratings(+1/-1). These data may help us in model optimization.  And we will consider sharing these data with public in the future.
