### ISSUE TITLE
A simple way to save 99% network data flowing and 3x speed up the generating with much more face quality 

### ISSUE THREAD

**Issue by lllyasviel** [makegirlsmoe/makegirls.moe_web#16]
step 1. generate about 1x10^7 face images with your tesla in about 24 hours on monday every week.
step 2. delete all the generated images on sunday every week.
step 3. do binary search each time your user requires a image and send them the 128p result in jpg version.

Because the AI do not need user to upload their sketch or highly Individualization like paintschainer or styletransfer, you can do as follow.

step 4. You can use discriminator to give "score" to the mentioned 1x10^7 face images when generating them in step 1 and sort this score in step 3 to give your user the best result.

**Comment by lllyasviel** [comment]
then even a 5 dollar server can hold the app, if someone write a fully php or asp or asp.net version.

**Comment by zhangjk95** [comment]
Thank you for your suggestion. However, we can't accept it.
This website is not only a tool for generating images, but also a demo that shows our research. Therefore, we can't simply return the result to users. It is essential to show how it really works, and users can even do some "hackings" to it (e.g. http://tosaka2.hatenablog.com/entry/2017/08/15/174439).

**Comment by lllyasviel** [comment]
Then the "how it really works" is more important than all these as follow?
1. 99% network data saving.
2. much more faster image giving.
3. much more higher image quality.
4. every one can run this app using his own server with very little money cost.

btw: the "hacking" will still works, if we use some simple trick

**Comment by zhangjk95** [comment]
The answer to your question is "yes", because that's the reason why we created this website.
Besides, the number of combinations of options is more than 4*10^4. To ensure that every user can get a unique image each time he/she request an image for his/her option, it requires a huge amount of pregenerated images, which is almost impossible.
Note that the "uniqueness" of image is very important because we don't wan't users to get a image that he/she has already seen on twitter timeline.

**Comment by lllyasviel** [comment]
easy.
1x10^7 is enough and not impossible.
delete the image every time you give it to a user will ensure the "unique". then if images is running out we can use step 1 every 3 days instead of a week.

**Comment by lllyasviel** [comment]
batchsize is 32
each batch use 1.5s in your tesla
then 1*10^7 takes 17.5 hours

**Comment by Anonymous066** [comment]
@lllyasviel 
你再混几年这个业界再过来跟我说，把这些图片做成缓存处理。
Too young, too simple, sometimes naive.

**Comment by lllyasviel** [comment]
@Anonymous066 
The main advantage of my idea is not only the cache. The most important thing is we can use discriminator to score these cache, then we can sort their score to achieve the best result.
And the problem of "unique" can be tackled by dynamic deleting as I mentioned above.
