### ISSUE TITLE
噗哈哈哈哈

### ISSUE THREAD

**Issue by Anonymous066** [makegirlsmoe/makegirls.moe_web#18]
https://twitter.com/kaKyoKsis/status/898986015997558784/photo/1?ref_src=twsrc%5Etfw&ref_url=http%3A%2F%2Fmake.girls.moe%2F
![default](https://user-images.githubusercontent.com/31143872/29489544-de5b6074-8555-11e7-8d5e-a12c49fd0543.png)

https://twitter.com/kamixadze/status/898987011318480896/photo/1
![default](https://user-images.githubusercontent.com/31143872/29489563-3328a4cc-8556-11e7-8f96-340d75c8adb0.png)

<hr></hr>

![default](https://user-images.githubusercontent.com/31143872/29489577-d368789a-8556-11e7-97a3-25b9080eddc3.png)

![default](https://user-images.githubusercontent.com/31143872/29489573-ab7a0934-8556-11e7-99d3-ddd7a7a7c7a4.png)
![default](https://user-images.githubusercontent.com/31143872/29489572-9e1c22fe-8556-11e7-806f-2f40a83e4951.png)

![default](https://user-images.githubusercontent.com/31143872/29489589-422aeb1e-8557-11e7-99df-fd26cccecabe.png)
![default](https://user-images.githubusercontent.com/31143872/29489606-970eaed6-8557-11e7-91d4-a123d0af4ae0.png)

![default](https://user-images.githubusercontent.com/31143872/29489616-de94f58a-8557-11e7-86fd-72a28436772a.png)

PS: I don't mind if you change the issue title.

**Comment by Anonymous066** [comment]
I am sorry about that. Does it is not enough data to feed and trains so generate that weird images instead?

**Comment by Aixile** [comment]
We also have no idea where the distortion comes from, maybe the model, maybe the dataset.
Actually, previous experiments on anime faces generation appear more likely to generate distorted images, we have improved the result by a large margin.
For the dataset, both quality and quantity of the training dataset play a key role, but building a high-quality training dataset is labor-intensive.
Anyway, GAN itself is a black box and not well studied, we look forward to improving the result along with the development of deep generative models
