### ISSUE TITLE
Allow to save/load random noises.

### ISSUE THREAD

**Issue by matsulib** [makegirlsmoe/makegirls.moe_web#2]
I am trying to generate good images.

As you've mentioned in [tips](http://make.girls.moe/#/tips), a good random noise is important for the better generation.
However, a random noise is reset when reloading or closing the browser tab.
There is no way to recall it.

So I would like to save/load random noises.
It  would be very useful when reproducing the good images found before.

**Comment by zhangjk95** [comment]
Thank you for your suggestion. We are working on it.

**Comment by matsulib** [comment]
@zhangjk95 Thank you for your response :)
I am looking forward to it!

**Comment by zhangjk95** [comment]
Closed by https://github.com/makegirlsmoe/makegirls.moe_web/commit/5be6da6654432dc40a809828257c792c5196102f
