### ISSUE TITLE
Defected background when generating with WebGPU 使用WebGPU生成图片背景异常

### ISSUE THREAD

**Issue by DEDZTBH** [makegirlsmoe/makegirls.moe_web#20]
![1](https://user-images.githubusercontent.com/12813869/29976588-1b1c5128-8f6d-11e7-8c2c-9fbd84f2f91e.png)
![1w](https://user-images.githubusercontent.com/12813869/29976589-1b3c3a74-8f6d-11e7-8e02-9b682365cdea.png)
![n1](https://user-images.githubusercontent.com/12813869/29976590-1b3eabe2-8f6d-11e7-9791-dfb8eee7975c.png)

While generating a image with WebGPU, there are large chunks of black space in the background. Provided here are the images generated on Chrome (normal) vs. generated with Safari Teh Preview WebGPU (defective), as well as the noise.
I am using MacBook Pro (Retina, 15-inch, Mid 2014) with NVIDIA GeForce GT 750M.

用WebGPU生成图片时背景会有大块的黑色。上面的图片是chrome生成的（正常）和用WebGPU生成的（不正常）。噪音也已经给出。
我是用的是MacBook Pro (Retina, 15-inch, Mid 2014)。显卡是 NVIDIA GeForce GT 750M。

**Comment by Aixile** [comment]
Thanks for reporting the issue, I will forward it to WebDNN after further investigation.
Since WebGPU is still an experimental feature, I am not sure whether the problem comes from WebGPU itself or the WebDNN framework.

**Comment by Aixile** [comment]
I suspect NaN comes from the batch normalization operation, it seems that NVIDIA GPUs have some precision problems with WebGPU. 
As a temporary remedy, we have converted all NaN to 1 in our web demo.

**Comment by Aixile** [comment]
This problem is solved in https://github.com/mil-tokyo/webdnn/commit/82840487dc357b1708573d61e9ebf3b54389e891
