### ISSUE TITLE
Internal Server Error when vote

### ISSUE THREAD

**Issue by icepeng** [makegirlsmoe/makegirls.moe_web#22]
Request on http://make.girls.moe/api/stat/rate reponse with 500 error

{"message":"could not find host matching read preference { mode: \"primary\", tags: [ {} ] } for set data1","error":{"code":133,"index":0,"errmsg":"could not find host matching read preference { mode: \"primary\", tags: [ {} ] } for set data1"

**Comment by Aixile** [comment]
Thanks for your report. Our background mongodb service crashed, and we have fixed it.
