### ISSUE TITLE
Please re-compile your model to support iOS 11

### ISSUE THREAD

**Issue by Kiikurage** [makegirlsmoe/makegirls.moe_web#24]
Yesterday, we updated WebDNN to support iOS11, new iOS which will be released next week.

iOS11 supports WebGPU, but some hardware-oriented constriction is different from macOS and re-compiling your model is needed.
Could you re-compile your model to support iOS11? it is not needed to modify your JavaScript frontend code.

**Comment by zhangjk95** [comment]
We recompiled our model in https://github.com/makegirlsmoe/makegirls.moe_web/commit/2cc6483424b24e6341c1e9f2424dced21c2f1103. Thanks for your kindly reminder!
