### ISSUE TITLE
The 'hat on' option mostly didn't add hats from what I tried

### ISSUE THREAD

**Issue by zori** [makegirlsmoe/makegirls.moe_web#5]
Maybe training DS has too few images with hats

**Comment by Aixile** [comment]
About 5% training images are assigned with `hat`  in our dataset (But the tag itself is generated by a classifier so it might be noisy),  we observed that tags related to shapes(hat, glasses) are much harder to be well learned compared to color tags.
We evaluated precision score for every tag, among them  'hat' is the lowest (15%) .

**Comment by zori** [comment]
Thanks for your explanation. Nevertheless, I felt it works great and results were very sharp and consistent (look like a human face) :clap:
