### ISSUE TITLE
Show the real deal

### ISSUE THREAD

**Issue by dsslimshaddy** [makegirlsmoe/makegirls.moe_web#6]
how its exactly done any description or guide will be good

**Comment by zhangjk95** [comment]
Please refer to our blog (https://makegirlsmoe.github.io/main/2017/08/14/news-english.html) and technical report (https://makegirlsmoe.github.io/assets/pdf/technical_report.pdf).

**Comment by Aixile** [comment]
It will take some time to clean up training scripts. All of us are working on the website part now because of the tremendous number of visits...
