### ISSUE TITLE
SVG and Config export

### ISSUE THREAD

**Issue by abhimanyu003** [makegirlsmoe/makegirls.moe_web#8]
It is a really nice project.
Is it possible to export the current noise and settings and can be tweaked later on?

Whats your thought on adding SVG support as well.

**Comment by lesderid** [comment]
I'm not sure what SVG support would do? The generated images aren't vector-based.

**Comment by abhimanyu003** [comment]
With SVG ( vector based ) graphic we never have to worry about the quality of the image.
It will give a free option to resize the image as much as you want.

In addition to this, it will make lot easier to create graphics when working with vector based tools like https://inkscape.org/en/

**Comment by zhangjk95** [comment]
I think you may have misunderstood the way how the project works. The images are not actually "drawed" using lines and shapes. They are generated by a deep neural network, and the output of our model is a 128x128 bitmap. I don't think there is anything to do with SVG.

**Comment by zhangjk95** [comment]
I think you may have misunderstood the way how the project works. The images are not actually "drawn" using lines and shapes. They are generated by a deep neural network, and the output of our model is a 128x128 bitmap. I don't think there is anything to do with SVG.
